name: Main
permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build stand-alone (linux-x64)
        run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true FactorioModUpdater/FactorioModUpdater.csproj
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./FactorioModUpdater/bin/Release/net8.0/linux-x64/publish/FactorioModUpdater
